---
title: "Tables for report (Feb 21st version)"
date: "`r Sys.Date()`"
author: "D. Erik Boonstra, MS"
output:
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
---

```{r setup, include = FALSE}
R <- list.files(path = "./R", pattern = "*.R", full.names = TRUE)
sapply(R, source, .GlobalEnv)
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo = FALSE, out.width = "100%", fig.align = "center")
```

# Correlation tables

## Clustered diseases
```{r}
load("./outputs/icd9-ss-series/clustering.RData")
corr_ssm <- corr_ssm[order(corr_ssm$rho_asm, decreasing = TRUE), ]
corr_ssm$rho_ssm <- format(round(corr_ssm$rho_ssm, 3), nsmall = 3)
corr_ssm$rho_asm <- format(round(corr_ssm$rho_asm, 3), nsmall = 3)
corr_ssm$rho_asm <- ifelse(
  test = corr_ssm$ccs_code %in% corr_asm$ccs_code,
  yes = paste0(corr_ssm$rho_asm, "*"),
  no = corr_ssm$rho_asm
)
row.names(corr_ssm) <- NULL
tab <- knitr::kable(
  x = corr_ssm,
  digits = 3, align = c("r", "l", "r", "r"),
  col.names = c(
    "CCS", "Disease", "Global correlation", "Local correlation"
  ),
  caption = paste0(
    "The global and local correlations for the diseases that are globally",
    " clustered with influenza for the primary ICD-9 cohort.",
    " The diseases marked with a * are globally and locally associated with",
    " influenza. Diseases are globally clustered with influenza if their ",
    " global correlation value is 0.6 or higher, while locally clustered ",
    " disease also have a local correlation 0.2 or higher.",
    " Global and local association indicates a causal relationship between the",
    " diseases and influenza."
  )
)
kableExtra::kable_styling(kable_input = tab)
```

## Summer diseases
```{r}
corr_sum <- subset(
  x = corr_all,
  subset = rho_ssm <= (-1 * ssm_threshold)
)
corr_sum <- corr_sum[order(corr_sum$rho_ssm, decreasing = TRUE), ]
row.names(corr_sum) <- NULL
tab <- knitr::kable(
  x = subset(corr_sum, select = c(ccs_code, disease, rho_ssm)),
  digits = 4, align = c("r", "l", "r"),
  col.names = c(
    "CCS", "Disease", "Global correlation"
  ),
  caption = paste0(
    "The diseases that are negatively correlated with influenza by having a",
    " correlation less than or equal to the correlation threshold of -0.6.",
    " These diseases are considered to peak in the summer months; thus,",
    " having summer seasonality."
  )
)
kableExtra::kable_styling(kable_input = tab)
```

# Attributable risk table
```{r}
icd_incidence_rds <- paste0(
  "./outputs/icd",
  c("9", "-crossover"),
  "-ss-series/incidence_change.rds"
)
age_incidence_rds <- paste0(
  "./outputs/age-",
  c(
    "less2", "2to4", "5to11",
    "12to17", "18to34", "35to44",
    "45to54", "55to64", "greater64"
  ),
  "-ss-series/incidence_change.rds"
)
incidence_rds <- c(icd_incidence_rds, age_incidence_rds)
incidence_change <- lapply(
  X = incidence_rds,
  FUN = function(x) {
    dat <- readRDS(file = x)
    ccs <- unique(dat$ccs_code)
    ccs <- ccs[order(ccs)]
    dat20 <- subset(
      x = dat,
      subset = pct == 0.2,
      select = c(ccs_code, relative_change)
    )
    dat20 <- dat20[order(dat20$ccs_code), ]
    dat20 <- format(100 * round(dat20$relative_change, 5), nsmall = 3)
    dat60 <- subset(
      x = dat,
      subset = pct == 0.6,
      select = c(ccs_code, relative_change)
    )
    dat60 <- dat60[order(dat60$ccs_code), ]
    dat60 <- format(100 * round(dat60$relative_change, 5), nsmall = 3)
    change <- paste0("(", dat20, "%, ", dat60, "%)")
    names(change) <- paste0("ccs", ccs)
    return(change)
  }
)
tab <- data.frame(dplyr::bind_rows(incidence_change))
tab <- tab[, order(as.integer(substr(names(tab), 4, nchar(names(tab)))))]
row.names(tab) <- c(
  "ICD-9", "ICD-crossover",
  "Age: <2", "Age: 2-4", "Age: 5-11",
  "Age: 12-17", "Age: 18-34", "Age: 35-44",
  "Age: 45-54", "Age: 55-64", "Age: >64"
)
tab <- t(tab)
tab <- cbind(tab, substr(row.names(tab), 4, nchar(row.names(tab))))
tab <- tab[, c(dim(tab)[2], seq_len(dim(tab)[2])[-dim(tab)[2]])]
colnames(tab)[1] <- "CCS"
row.names(tab) <- NULL
options(knitr.kable.NA = "")
kbl_tab <- knitr::kable(
  x = tab, format = "html", col.names = colnames(tab),
  align = paste0(
    "r",
    paste0(rep("c", dim(tab)[2] - 1), collapse = ""),
    collapse = ""
  ),
  caption = paste0(
    "The percent reduction in incidence rate for the diseases that are",
    " globally and locally clustered with influenza given a reduction in the",
    " influenza incidence rate",
    " for primary and seconday disease cohorts,",
    " where (L%, R%) refers to the percent reduction",
    " in incidence rate for a disease assuming the influenza incidence rate",
    " decreased by (20%, 60%).",
    " Diseases with no reduction in incidence rate reported indicate the",
    " disease was not globally and locally assoicated with influenza, which",
    " means any attributable risk estimate would not be",
    " statistically significant."
  )
)
kableExtra::kable_styling(kable_input = kbl_tab, font_size = 7)
```

# CCS table
```{r}
ccs_labels <- utils::read.csv(file = "./data/ccs-series/ccs_labels.csv")
ccs_labels <- subset(
  x = ccs_labels,
  subset = ccs_code %in% as.integer(tab[, 1])
)
ccs_labels <- ccs_labels[order(ccs_labels$ccs_code), ]
row.names(ccs_labels) <- NULL
kbl_tab <- knitr::kable(
  x = ccs_labels, format = "html", col.names = c("CCS", "Disease"),
  align = "ll",
  caption = paste0(
    "Disease descriptions for CCS codes identified as being globally and",
    " locally clustered with influenza in any of the primary and seconday",
    " disease cohorts."
  )
)
kableExtra::kable_styling(kable_input = kbl_tab)
```