---
title: "Tables for report (Feb 21st version)"
date: "`r Sys.Date()`"
author: "D. Erik Boonstra, MS"
output:
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
---

```{r setup, include = FALSE}
R <- list.files(path = "./R", pattern = "*.R", full.names = TRUE)
sapply(R, source, .GlobalEnv)
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo = FALSE, out.width = "100%", fig.align = "center")
```

# Table 2
```{r}
tab2 <- utils::read.csv(
  file = "./tables/influenza-burden-report-21Feb-eb/tab2.csv",
  na.string = "", skip = 1, header = FALSE
)
tab2 <- as.matrix(tab2)
colnames(tab2) <- c(
  "CCS", "Age: <2", "Age: 2-4", "Age: 5-11",
  "Age: 12-17", "Age: 18-34", "Age: 35-44",
  "Age: 45-54", "Age: 55-64", "Age: >64"
)
options(knitr.kable.NA = "")
kbl_tab <- knitr::kable(
  x = tab2, format = "html", col.names = colnames(tab2),
  align = paste0(
    "r",
    paste0(rep("c", dim(tab2)[2] - 1), collapse = ""),
    collapse = ""
  ),
  caption = paste0(
    "The global correlation values for all the disease that were ever",
    " locally correlated with influenza based on age group. Diseases",
    " with missing correlation values are an indication that for the age group",
    " of interest the disease was not globally and locally correlated with",
    " influenza."
  )
)
kableExtra::kable_styling(kable_input = kbl_tab, font_size = 10)
```

# Table 3
```{r}
tab3 <- utils::read.csv(
  file = "./tables/influenza-burden-report-21Feb-eb/tab3.csv",
  na.string = "", skip = 1, header = FALSE
)
tab3 <- as.matrix(tab3)
colnames(tab3) <- c(
  "CCS", "Age: <2", "Age: 2-4", "Age: 5-11",
  "Age: 12-17", "Age: 18-34", "Age: 35-44",
  "Age: 45-54", "Age: 55-64", "Age: >64"
)
options(knitr.kable.NA = "")
kbl_tab <- knitr::kable(
  x = tab3, format = "html", col.names = colnames(tab3),
  align = paste0(
    "r",
    paste0(rep("c", dim(tab3)[2] - 1), collapse = ""),
    collapse = ""
  ),
  caption = paste0(
    "A selection correlation values for diseases that are classified as",
    " peaking in the summer. A disease is classified as a summer disease by",
    " having a global correlation of -0.6 (i.e., -1 * global correlation",
    " threshold) with the seasonal component of influenza based on the age",
    " group. The diseases presented here have a correlation value of -0.9 or",
    " higher. A correlation value is missing if for the age group of interest",
    " the correlation value was not less than -0.9."
  )
)
kableExtra::kable_styling(kable_input = kbl_tab, font_size = 10)
```

# Table 4
```{r}
tab4 <- utils::read.csv(
  file = "./tables/influenza-burden-report-21Feb-eb/tab4.csv",
  na.string = "", skip = 1, header = FALSE
)
tab4 <- as.matrix(tab4)
colnames(tab4) <- c(
  "CCS", "Age: <2", "Age: 2-4", "Age: 5-11",
  "Age: 12-17", "Age: 18-34", "Age: 35-44",
  "Age: 45-54", "Age: 55-64", "Age: >64"
)
options(knitr.kable.NA = "")
kbl_tab <- knitr::kable(
  x = tab4, format = "html", col.names = colnames(tab4),
  align = paste0(
    "r",
    paste0(rep("c", dim(tab4)[2] - 1), collapse = ""),
    collapse = ""
  ),
  caption = paste0(
    "The local correlation values for all the disease that were ever",
    " locally correlated with influenza based on age group. Diseases",
    " with missing correlation values are an indication that for the age group",
    " of interest the disease was not globally and locally correlated with",
    " influenza."
  )
)
kableExtra::kable_styling(kable_input = kbl_tab, font_size = 10)
```

# Table 5
```{r}
tab5 <- utils::read.csv(
  file = "./tables/influenza-burden-report-21Feb-eb/tab5.csv",
  na.string = "", skip = 1, header = FALSE
)
tab5 <- as.matrix(tab5)
colnames(tab5) <- c(
  "CCS", "Age: <2", "Age: 2-4", "Age: 5-11",
  "Age: 12-17", "Age: 18-34", "Age: 35-44",
  "Age: 45-54", "Age: 55-64", "Age: >64"
)
options(knitr.kable.NA = "")
kbl_tab <- knitr::kable(
  x = tab5, format = "html", col.names = colnames(tab5),
  align = paste0(
    "r",
    paste0(rep("c", dim(tab5)[2] - 1), collapse = ""),
    collapse = ""
  ),
  caption = paste0(
    "The percent reduction in incidence rate for the diseases that are",
    " globally and locally clustered with influenza given a reduction in the",
    " influenza incidence rate",
    " for primary and seconday disease cohorts,",
    " where L%, R% refers to the percent reduction",
    " in incidence rate for a disease assuming the influenza incidence rate",
    " decreased by 20%, 60%.",
    " Diseases with no reduction in incidence rate reported indicate the",
    " disease was not globally and locally assoicated with influenza, which",
    " means any attributable risk estimate would not be",
    " statistically significant."
  )
)
kableExtra::kable_styling(kable_input = kbl_tab, font_size = 7)
```

# Table 6
```{r}
tab6 <- utils::read.csv(
  file = "./tables/influenza-burden-report-21Feb-eb/tab6.csv",
  na.string = "", skip = 1, header = FALSE
)
tab6 <- as.matrix(tab6)
colnames(tab6) <- c("CCS", "Disease description")
kbl_tab <- knitr::kable(
  x = tab6, format = "html", col.names = colnames(tab6),
  align = "ll",
  caption = paste0(
    "Disease descriptions for CCS codes identified as being globally",
    " and locally correlated with influenza, and diseases that peak in",
    " the summer."
  )
)

kableExtra::kable_styling(kable_input = kbl_tab)
```